openapi: 3.0.0
info:
  title: anyware_coligo_db
  version: 1.0.0
servers:
  - url: http://{{domain}}{{channel}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: auth
  - name: Announcement
paths:
  /auth/signup:
    post:
      tags:
        - auth
      summary: signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Ahmed
                userName: '@afmin3'
                password: Password-123
                cPassword: Password-123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userName: '@afmin3'
                password: Password-123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/logout:
    post:
      tags:
        - auth
      summary: logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: '{{tokenPassword}} {{token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /announcement/add:
    post:
      tags:
        - Announcement
      summary: addAnnouncement
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                topic: hello world
                desc: announcementannouncementannouncementannouncement
      security:
        - bearerAuth: []
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: '{{tokenPassword}} {{token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /announcement/{id}:
    get:
      tags:
        - Announcement
      summary: getAnnouncementById
      security:
        - bearerAuth: []
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: '{{tokenPassword}} {{token}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 63cacf1c13ef8d8f038b1260
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /announcement/:
    get:
      tags:
        - Announcement
      summary: getAllAnnouncements
      security:
        - bearerAuth: []
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: '{{tokenPassword}} {{token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /announcement/{id}/update:
    patch:
      tags:
        - Announcement
      summary: updateAnnouncementById
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                topic: hello world 2222222222222
                desc: announcementannouncementannouncementannouncement
      security:
        - bearerAuth: []
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          example: '{{tokenPassword}} {{token}}'
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 63cacf1c13ef8d8f038b1260
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
