// count
export const COUNT_CHANGE = 'COUNT_CHANGE';

// sidebar
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

// sidebar
export const ADD_USER_FROM_API = 'ADD_USER_FROM_API';
export const ADD_USER_FROM_BROWSER_STORAGE = 'ADD_USER_FROM_BROWSER_STORAGE';
export const DELETE_USER_FROM_BROWSER_STORAGE = 'DELETE_USER_FROM_BROWSER_STORAGE';
